image: tmaier/docker-compose:latest

variables:
  DOCKER_DRIVER: overlay2
  GIT_SUBMODULE_STRATEGY: normal

test:
  services:
  - docker:dind
  stage: test
  script:
  - docker info
  - docker-compose --version
  - apk add --update bash
  - apk add --update git
  - cp docker-compose.prod.yml.template docker-compose.prod.yml
  - cp variables.sh.template variables.sh
  - chmod +x variables.sh
  - sed -i 's/echo variables.sh/#echo variables.sh/' variables.sh
  - export IS_TESTING=true
  - ./dc pull --quiet tim
  - ./dc run --rm --no-deps --workdir /service tim mypy -p timApp
  - ./dc pull --quiet
  - ./npmi
  - ./js
  - ./run_tests.sh
  artifacts:
    name: failed_screenshots
    when: always
    paths:
    - screenshots

code_navigation:
  stage: test  # not really a test, but we want to execute this in parallel
  image: node:lts
  script:
  - cd timApp
  - npm install
  - npm install -g @sourcegraph/lsif-tsc
  - lsif-tsc -p .
  artifacts:
    reports:
      lsif: timApp/dump.lsif
