version: "3"
services:
 tim:
  depends_on:
   - funnel
   - ts-watcher
 nginx:
  ports:
   - "${NGINX_PORT}:80"
 funnel:
  image: timimages/funnel:latest
  volumes:
   - ./funnel:/service
   - ./tim_logs/funnel:/var/log/funnel
  working_dir: /service
  command: ${FUNNEL_COMMAND}
  restart: unless-stopped
 ts-watcher:
  image: timimages/tim:${TIM_IMAGE_TAG}
  volumes:
   - .:/service
  working_dir: /service/timApp/static/scripts
  command: jspm bundle tim/main + tim/slide - "(tim/main + tim/slide - [tim/**/*])" build/tim.js -wm
  restart: unless-stopped
