version: "3"
services:
 tim:
  depends_on:
   - funnel
   - ts-watcher
 nginx:
  ports:
   - "${NGINX_PORT}:80"
 funnel:
  image: timimages/funnel:latest
  volumes:
   - ./funnel:/service/funnel
   - ./tim_logs/funnel:/var/log/funnel
  working_dir: /service/funnel
  command: ${FUNNEL_COMMAND}
  restart: unless-stopped
  environment:
   PYTHONPATH: /service
 ts-watcher:
  image: timimages/tim:${TIM_IMAGE_TAG}
  volumes:
   - .:/service
   - /opt/jspm_cache:/root/.jspm
  working_dir: /service/timApp/static/scripts
  command: jspm bundle tim/main + tim/document/slide - "(tim/main + tim/document/slide - [tim/**/*])" build/tim.js -wm
  restart: unless-stopped
