version: "3"
services:
 tim:
  command: /usr/sbin/sshd -D
  ports:
   - "49999:22"
  depends_on:
   - postgresql-test
   - postgresql-tempdb-test
   - chrome
  tmpfs:
   - /tmp
 postgresql:
  ports:
   - "5432:5432"
 postgresql-tempdb:
  ports:
   - "5434:5432"
 postgresql-test:
  image: postgres:9.5
  ports:
   - "5433:5432"
  tmpfs:
   - /var/lib/postgresql/data
 postgresql-tempdb-test:
  image: postgres:9.5
  tmpfs:
   - /var/lib/postgresql/data
 imagex:
  image: timimages/cs3sudo:compose
  volumes:
   - ./timApp/modules/imagex:/imagex:ro
   - ./timApp/modules/py:/py:ro
  working_dir: /imagex
  command: ${IMAGEX_DEV_COMMAND:-/usr/sbin/sshd -D}
  ports:
   - "49995:22"
 pali:
  image: timimages/palisudo:compose
  build:
   context: ./timApp/modules/pali
   dockerfile: DockerfileS
  command: ${PALI_DEV_COMMAND:-/usr/sbin/sshd -D}
  ports:
   - "49997:22"
 csplugin:
  image: timimages/cs3sudo:compose
  build:
   context: ./timApp/modules/cs
   dockerfile: DockerfileS
  command: ${CSPLUGIN_DEV_COMMAND:-/usr/sbin/sshd -D}
  ports:
   - "49998:22"
 showfile:
  image: timimages/cs3sudo:compose
  build:
   context: ./timApp/modules/cs
   dockerfile: DockerfileS
  volumes:
   - ./timApp/modules/svn:/svn:ro
   - ./timApp/modules/py:/py:ro
  working_dir: /svn
  command: ${SVNPLUGIN_DEV_COMMAND:-/usr/sbin/sshd -D}
  ports:
   - "49996:22"
 chrome:
  image: selenium/standalone-chrome:3.8.1
  tmpfs:
   - /tmp
   - /home/seluser
 nginx:
  image: timimages/local_nginx_dev:compose
  build:
   args:
    MAIN_CONFIG: tim_dev.conf
  ports:
   - "${NGINX_PORT}:80"
