version: "3.7"
x-common-agent:
 &common-agent
 tmpfs:
  - /run/sshd
  - /home/agent/.pycharm_helpers
  - /root/.pycharm_helpers
x-common-root:
 &common-root
 tmpfs:
  - /run/sshd
  - /root/.pycharm_helpers
x-mailman-common-env:
 &mailman-common-env
  DATABASE_TYPE: sqlite
  DATABASE_URL: sqlite:////opt/mailmandb/mailmanweb.db
  DATABASE_CLASS: mailman.database.sqlite.SQLiteDatabase
  HYPERKITTY_API_KEY: test

services:
 tim:
  << : *common-root
  command: /usr/sbin/sshd -D
  ports:
   - "49999:22"
  depends_on:
   - postgresql-test
 postgresql:
  ports:
   - "5432:5432"
 postgresql-test:
  image: postgres:11
  ports:
   - "5433:5432"
  tmpfs:
   - /var/lib/postgresql/data
  restart: unless-stopped
  environment:
   POSTGRES_PASSWORD: postgresql
 imagex:
  << : *common-root
  image: timimages/cs3sudo:rust
  command: ${IMAGEX_DEV_COMMAND:-/usr/sbin/sshd -D}
  ports:
   - "49995:22"
 pali:
  << : *common-root
  command: ${PALI_DEV_COMMAND:-/usr/sbin/sshd -D}
  ports:
   - "49997:22"
 fields:
  << : *common-root
  command: ${TEXTFIELD_DEV_COMMAND:-/usr/sbin/sshd -D}
  ports:
   - "49990:22"
 jsrunner:
  << : *common-root
  command: ${JSRUNNER_DEV_COMMAND:-/usr/sbin/sshd -D}
  ports:
   - "49991:22"
 drag:
  << : *common-root
  command: ${DRAG_DEV_COMMAND:-/usr/sbin/sshd -D}
  ports:
   - "49980:22"
 feedback:
  << : *common-root
  command: ${FEEDBACK_DEV_COMMAND:-/usr/sbin/sshd -D}
  ports:
   - "49978:22"
 csplugin:
  << : *common-agent
  image: timimages/cs3sudo:rust
  build:
   context: ./timApp/modules/cs
   dockerfile: DockerfileS
  command: ${CSPLUGIN_DEV_COMMAND:-/usr/sbin/sshd -D}
  ports:
   - "49998:22"
 stack-api-server:
  << : *common-root
  image: timimages/stack-api:latest-dev
  restart: unless-stopped
  ports:
   - "49992:22"
 showfile:
  << : *common-agent
  image: timimages/cs3sudo:rust
  build:
   context: ./timApp/modules/cs
   dockerfile: DockerfileS
  command: ${SVNPLUGIN_DEV_COMMAND:-/usr/sbin/sshd -D}
  ports:
   - "49996:22"
 mailman-core:
  image: timimages/mailman-core:latest
  restart: unless-stopped
  profiles:
   - dev_mailman
  volumes:
   - ./mailman/db:/opt/mailmandb
   - ./mailman/core:/opt/mailman
  environment:
   <<: *mailman-common-env
 mailman-web:
  image: timimages/mailman-web:latest
  restart: unless-stopped
  profiles:
   - dev_mailman
  depends_on:
   - mailman-core
  volumes:
   - ./mailman/db:/opt/mailmandb
   - ./mailman/web:/opt/mailman-web-data
   - ./mailman/messages:/tmp/mailman-messages
  environment:
   <<: *mailman-common-env
   SECRET_KEY: test
   MAILMAN_ADMIN_USER: admin
   MAILMAN_ADMIN_EMAIL: admin@example.com
   SERVE_FROM_DOMAIN: localhost
   URL_BASE_DIR: mailman3
 caddy:
  volumes:
     - ${CADDY_MAILMAN_STATIC_DIR:?}:/var/www/mailman3/static