version: "3"
services:
 tim:
  image: timimages/tim:${TIM_IMAGE_TAG}
  build: ./timApp
  depends_on:
   - postgresql
   - csplugin
   - pali
   - showfile
   - haskellplugins
   - imagex
   - uploader
   - dumbo
  volumes:
   - .:/service
   - ${LOG_DIR}:/service/tim_logs
   - ${FILES_ROOT}:/tim_files
  working_dir: /service/timApp
  command: python3 launch.py --with-gunicorn
  environment:
   FLASK_APP: tim_app.py
   PYTHONPATH: /service:/usr/local/lib/python3.6/dist-packages
   COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
   TIM_SETTINGS: ${CONFIG_FILE}
   TIM_HOST: ${TIM_HOST}
  restart: unless-stopped
 postgresql:
  image: postgres:9.5
  volumes:
   - data:/var/lib/postgresql/data
  restart: unless-stopped
 csplugin:
  image: timimages/cs3:compose
  build: ./timApp/modules/cs
  volumes:
   - ./timApp/modules/cs:/cs
   - /var/run/docker.sock:/var/run/docker.sock
   - ./timApp/modules/cs/generated:/csgenerated
   - ./timApp/modules/cs/static:/csstatic:ro
   - ./timApp/modules/py:/py:ro
   - /tmp/${COMPOSE_PROJECT_NAME}_uhome:/tmp
  working_dir: /cs
  command: ./startPlugins.sh
  environment:
   PYTHONUNBUFFERED: "1"
   TIM_ROOT: ${TIM_ROOT}
   COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
  user: root
  restart: unless-stopped
 haskellplugins:
  image: timimages/haskellplugins:latest
  build:
   context: ./timApp/modules/Haskell
   dockerfile: Dockerfile
  volumes:
   - ./timApp/modules/Haskell:/Haskell
  working_dir: /Haskell
  command: ./startAll.sh
  restart: unless-stopped
 showfile:
  image: timimages/svn:latest
  build: ./timApp/modules/svn
  volumes:
   - ./timApp/modules/svn:/svn:ro
   - ./timApp/modules/py:/py:ro
  working_dir: /svn
  command: ./startAll.sh
  restart: unless-stopped
 imagex:
  image: timimages/cs3:compose
  volumes:
   - ./timApp/modules/imagex:/imagex:ro
   - ./timApp/modules/py:/py:ro
  working_dir: /imagex
  command: ./startAll.sh
  restart: unless-stopped
 pali:
  image: timimages/pali:compose
  build: ./timApp/modules/pali
  volumes:
   - ./timApp/modules/pali:/pali:ro
   - ./timApp/modules/py:/py:ro
  working_dir: /pali
  command: ./startAll.sh
  restart: unless-stopped
 uploader:
  image: villet/uploaderplugin:13_10_16_15
  command: ${UPLOADER_COMMAND}
  restart: unless-stopped
 nginx:
  image: timimages/local_nginx:compose
  build:
   context: ./local_nginx
  depends_on:
   - tim
  volumes:
   - ./timApp/modules/cs/static:/csstatic:ro
   - ./timApp/modules/cs/generated:/csgenerated:ro
   - ./timApp/static:/static:ro
  restart: unless-stopped
 dumbo:
  image: timimages/dumbo:${TIM_IMAGE_TAG}
  build:
   context: ./Dumbo
   dockerfile: Dockerfile
   args:
    TIM_IMAGE_TAG: ${TIM_IMAGE_TAG}
  command: ./Dumbo --port 5000 --cacheDir /dumbocache --tmpDir /dumbotmp
  working_dir: /Dumbo
  volumes:
   - ./Dumbo/cache:/dumbocache
   - ./Dumbo/tmp:/dumbotmp
  logging:
   driver: none
  restart: unless-stopped
volumes:
 data:
