version: "3"
services:
 tim:
  command: /usr/sbin/sshd -D
  ports:
   - "49999:22"
  depends_on:
   - postgresql
   - postgresql-tempdb
   - postgresql-test
   - postgresql-tempdb-test
   - csplugin
   - pali
   - showfile
   - haskellplugins
   - imagex
   - uploader
   - chrome
   - dumbo
   - ts-watcher
   - funnel
 postgresql:
  ports:
   - "5432:5432"
 postgresql-test:
  image: postgres:9.5
 postgresql-tempdb-test:
  image: postgres:9.5
 pali:
  image: timimages/palisudo:compose
  build:
   context: ./timApp/modules/pali
   dockerfile: DockerfileS
  command: ${PALI_DEV_COMMAND:-/usr/sbin/sshd -D}
  ports:
   - "49997:22"
 csplugin:
  image: timimages/cs3sudo:compose
  build:
   context: ./timApp/modules/cs
   dockerfile: DockerfileS
  command: ${CSPLUGIN_DEV_COMMAND:-/usr/sbin/sshd -D}
  ports:
   - "49998:22"
 showfile:
  image: timimages/cs3sudo:compose
  build:
   context: ./timApp/modules/cs
   dockerfile: DockerfileS
  volumes:
   - ./timApp/modules/svn:/svn:ro
   - ./timApp/modules/py:/py:ro
  working_dir: /svn
  command: ${SVNPLUGIN_DEV_COMMAND:-/usr/sbin/sshd -D}
  ports:
   - "49996:22"
 chrome:
  image: selenium/standalone-chrome:3.6.0
 nginx:
  image: timimages/local_nginx_dev:compose
  build:
   args:
    MAIN_CONFIG: tim_dev.conf
 ts-watcher:
  command: /bin/true  # in development, the watcher is supposed to be launched from IDE
 tests:
  image: timimages/tim:${TIM_IMAGE_TAG}
  command: "python3 -m unittest ${TEST_PARAMS:-discover tests/ 'test_*.py' .}"
  volumes:
   - .:/service:ro
   - ./screenshots:/service/screenshots:rw
   - ./timApp/static/testgen:/service/timApp/static/testgen:rw
   - ./timApp/static/.webassets-cache:/service/timApp/static/.webassets-cache:rw
   - ./timApp/static/scripts:/service/timApp/static/scripts:rw
  environment:
   TIM_SETTINGS: testconfig.py
   PYTHONPATH: /service
  depends_on:
   - tim
  tmpfs:
   - /tmp/doctest_files
  working_dir: /service/timApp
