version: "3.7"
x-common-agent:
 &common-agent
 tmpfs:
  - /run/sshd
  - /home/agent/.pycharm_helpers
  - /root/.pycharm_helpers
x-common-root:
 &common-root
 tmpfs:
  - /run/sshd
  - /root/.pycharm_helpers
services:
 tim:
  << : *common-root
  command: /usr/sbin/sshd -D
  ports:
   - "49999:22"
  depends_on:
   - postgresql-test
   - chrome
 postgresql:
  ports:
   - "5432:5432"
 postgresql-test:
  image: postgres:11
  ports:
   - "5433:5432"
  tmpfs:
   - /var/lib/postgresql/data
  restart: unless-stopped
  environment:
   POSTGRES_PASSWORD: postgresql
 imagex:
  << : *common-root
  image: timimages/cs3sudo:rust
  volumes:
   - ./timApp/modules/imagex:/imagex:ro
   - ./timApp/modules/py:/py:ro
  working_dir: /imagex
  command: ${IMAGEX_DEV_COMMAND:-/usr/sbin/sshd -D}
  ports:
   - "49995:22"
 pali:
  << : *common-root
  command: ${PALI_DEV_COMMAND:-/usr/sbin/sshd -D}
  ports:
   - "49997:22"
 fields:
  << : *common-root
  command: ${TEXTFIELD_DEV_COMMAND:-/usr/sbin/sshd -D}
  ports:
   - "49990:22"
 jsrunner:
  << : *common-root
  command: ${JSRUNNER_DEV_COMMAND:-/usr/sbin/sshd -D}
  ports:
   - "49951:22"
 drag:
  << : *common-root
  command: ${DRAG_DEV_COMMAND:-/usr/sbin/sshd -D}
  ports:
   - "49980:22"
 feedback:
  << : *common-root
  command: ${FEEDBACK_DEV_COMMAND:-/usr/sbin/sshd -D}
  ports:
   - "49978:22"
 csplugin:
  << : *common-agent
  image: timimages/cs3sudo:rust
  build:
   context: ./timApp/modules/cs
   dockerfile: DockerfileS
  command: ${CSPLUGIN_DEV_COMMAND:-/usr/sbin/sshd -D}
  ports:
   - "49998:22"
 stack-api-server:
  << : *common-root
  image: timimages/stack-debug
  build:
    context: ./stack
    dockerfile: DockerfileDebug
  security_opt:
   - seccomp:unconfined
  volumes:
   - ./timApp/modules/cs/generated/stackplots:/var/data/api/stack/plots:rw
   - ./stack/plots:/var/data/api/stack/plots:rw
   - ./stack/plots:/var/www/html/plots:rw
   - ./stack/api:/var/www/html/api:rw
   - ./stack/stack:/var/www/html/stack:rw
   - ./stack/blob:/var/www/html/api/blob:rw
   - ./stack/api/config.php.docker:/var/www/html/config.php:rw
   - ./stack/entrypoint_install_and_run_debug.sh:/var/www/html/entrypoint_install_and_run.sh
  restart: unless-stopped
  ports:
   - "49992:22"
 showfile:
  << : *common-agent
  image: timimages/cs3sudo:rust
  build:
   context: ./timApp/modules/cs
   dockerfile: DockerfileS
  volumes:
   - ./timApp/modules/svn:/svn:ro
   - ./timApp/modules/py:/py:ro
  working_dir: /svn
  command: ${SVNPLUGIN_DEV_COMMAND:-/usr/sbin/sshd -D}
  ports:
   - "49996:22"
 chrome:
  image: selenium/standalone-chrome:3.141.59-zirconium
  tmpfs:
   - /home/seluser
   - /run/supervisor
   - /tmp
   - /var/log/supervisor
  volumes:
   - /dev/shm:/dev/shm
  restart: unless-stopped
  read_only: true
 nginx:
  image: timimages/local_nginx_dev:compose
  build:
   args:
    MAIN_CONFIG: tim_dev.conf
  ports:
   - "127.0.0.1:81:80"
