version: "3"
services:
 tim:
  command: /usr/sbin/sshd -D
  ports:
   - "49999:22"
  depends_on:
   - postgresql
   - postgresql-tempdb
   - postgresql-test
   - postgresql-tempdb-test
   - csplugin
   - pali
   - showfile
   - haskellplugins2
   - imagex
   - uploader
   - chrome
   - prebuilt_dumbo
   - ts-watcher
 postgresql:
  ports:
   - "5432:5432"
 postgresql-test:
  image: postgres:9.5
 postgresql-tempdb-test:
  image: postgres:9.5
# csplugin:
#  command: /usr/sbin/sshd -D
#  ports:
#   - "49998:22"
 nginx:
  image: timimages/local_nginx_dev:latest
  build:
   args:
    MAIN_CONFIG: tim_dev.conf
 ts-watcher:
  command: /bin/true  # in development, the watcher is supposed to be launched from IDE
 tests:
  image: timimages/tim:${TIM_IMAGE_TAG}
  command: "python3 -m unittest ${TEST_PARAMS:-discover tests/ 'test_*.py' .}"
  volumes:
   - .:/service:ro
   - ./timApp/static/testgen:/service/timApp/static/testgen:rw
   - ./timApp/static/.webassets-cache:/service/timApp/static/.webassets-cache:rw
   - ./timApp/static/scripts:/service/timApp/static/scripts:rw
  environment:
   TIM_SETTINGS: testconfig.py
  depends_on:
   - tim
  tmpfs:
   - /tmp/doctest_files
  working_dir: /service/timApp
