version: "3"
services:
 tim:
  command: /usr/sbin/sshd -D
  ports:
   - "49999:22"
  depends_on:
   - postgresql-test
   - chrome
  tmpfs:
   - /tmp
 postgresql:
  ports:
   - "5432:5432"
 postgresql-test:
  image: postgres:9.5
  ports:
   - "5433:5432"
  tmpfs:
   - /var/lib/postgresql/data
 imagex:
  image: timimages/cs3sudo:rust
  volumes:
   - ./timApp/modules/imagex:/imagex:ro
   - ./timApp/modules/py:/py:ro
  working_dir: /imagex
  command: ${IMAGEX_DEV_COMMAND:-/usr/sbin/sshd -D}
  ports:
   - "49995:22"
 pali:
  image: timimages/palisudo:compose
  build:
   context: ./timApp/modules/pali
   dockerfile: DockerfileS
  command: ${PALI_DEV_COMMAND:-/usr/sbin/sshd -D}
  ports:
   - "49997:22"
 csplugin:
  image: timimages/cs3sudo:rust
  build:
   context: ./timApp/modules/cs
   dockerfile: DockerfileS
  command: ${CSPLUGIN_DEV_COMMAND:-/usr/sbin/sshd -D}
  ports:
   - "49998:22"
 stack-api-server:
  image: timimages/stack-debug
  build:
    context: /var/www/api
    dockerfile: DockerfileDebug
  security_opt:
   - seccomp:unconfined
  volumes:
   - /opt/tim/timApp/modules/cs/generated/stackplots:/var/data/api/stack/plots:rw
   - /var/www/api/plots:/var/data/api/stack/plots:rw
   - /var/www/api/plots:/var/www/html/plots:rw
   - /var/www/api/api:/var/www/html/api:rw
   - /var/www/api/stack:/var/www/html/stack:rw
   - /var/www/blob:/var/www/html/api/blob:rw
   - /var/www/api/api/config.php.docker:/var/www/html/config.php:rw
   - /var/www/api/entrypoint_install_and_run_debug.sh:/var/www/html/entrypoint_install_and_run.sh
  restart: unless-stopped
  ports:
   - "90:80"
   - "49992:22"
   - "9000:9000"
 showfile:
  image: timimages/cs3sudo:rust
  build:
   context: ./timApp/modules/cs
   dockerfile: DockerfileS
  volumes:
   - ./timApp/modules/svn:/svn:ro
   - ./timApp/modules/py:/py:ro
  working_dir: /svn
  command: ${SVNPLUGIN_DEV_COMMAND:-/usr/sbin/sshd -D}
  ports:
   - "49996:22"
 chrome:
  image: selenium/standalone-chrome:3.8.1
  tmpfs:
   - /tmp
   - /home/seluser
 nginx:
  image: timimages/local_nginx_dev:compose
  build:
   args:
    MAIN_CONFIG: tim_dev.conf
  ports:
   - "${NGINX_PORT}:80"
