version: "3.7"
services:
 tim:
  depends_on:
   - postgresql-test
   - chrome
  tmpfs:
   - /tmp
  command: "sleep infinity"
 postgresql:
  command: "sleep infinity"
 postgresql-test:
  image: postgres:11
  tmpfs:
   - /var/lib/postgresql/data
  environment:
   POSTGRES_PASSWORD: postgresql
 chrome:
  image: selenium/standalone-chrome:3.141.59-uranium
  tmpfs:
   - /home/seluser
   - /run/supervisor
   - /tmp
   - /var/log/supervisor
  read_only: true
 nginx:
  image: timimages/local_nginx_dev:compose
  build:
   args:
    MAIN_CONFIG: tim_dev.conf
 tests:
  image: timimages/tim:${TIM_IMAGE_TAG}
  command: "python3 -m unittest ${TEST_PARAMS:-discover tests/ 'test_*.py' .}"
  volumes:
   - .:/service:rw
  environment:
   TIM_SETTINGS: testconfig.py
   PYTHONPATH: /service:/service/timApp/modules/py
   GITLAB_CI: ${GITLAB_CI:-false}
  depends_on:
   - nginx
  tmpfs:
   - /tmp
   - /tim_files
   - /cache
  working_dir: /service/timApp
  read_only: true
# Disable some images and services that are not used in tests.
 stack-api-server:
  image: timimages/tim:${TIM_IMAGE_TAG}
  command: "sleep infinity"
 timagent:
  image: timimages/tim:${TIM_IMAGE_TAG}
  command: "sleep infinity"
 uploader:
  image: timimages/tim:${TIM_IMAGE_TAG}
  command: "sleep infinity"
