version: "3"
services:
 tim:
  image: timimages/tim:${TIM_IMAGE_TAG}
  build: ./timApp
  depends_on:
   - postgresql
   - postgresql-tempdb
   - csplugin
   - pali
   - showfile
   - haskellplugins
   - imagex
   - uploader
   - prebuilt_dumbo
   - ts-watcher
   - funnel
  volumes:
   - .:/service
   - ${LOG_DIR}:/service/tim_logs
   - ${FILES_ROOT}:/tim_files
  working_dir: /service/timApp
  command: python3 launch.py --with-gunicorn
  environment:
   FLASK_APP: tim_app.py
   PYTHONPATH: /service:/usr/local/lib/python3.6/dist-packages
   COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
   TIM_SETTINGS: ${CONFIG_FILE}
   TIM_HOST: ${TIM_HOST}
 funnel:
  image: timimages/funnel:latest
  volumes:
   - ./funnel:/service
   - ./tim_logs/funnel:/var/log/funnel
  working_dir: /service
  command: ${FUNNEL_COMMAND}
 postgresql:
  image: postgres:9.5
  volumes:
   - data:/var/lib/postgresql/data
#  healthcheck:
#   test: ["CMD-SHELL", "psql -h 'localhost' -U 'postgres' -c '\\l'"]
#   interval: 30s
#   timeout: 1s
#   retries: 10
 postgresql-tempdb:
  image: postgres:9.5
 csplugin:
  image: timimages/cs3:compose
  build: ./timApp/modules/cs
  volumes:
   - ./timApp/modules/cs:/cs
   - /var/run/docker.sock:/var/run/docker.sock
   - ./timApp/modules/cs/generated:/csgenerated
   - ./timApp/modules/cs/static:/csstatic:ro
   - ./timApp/modules/py:/py:ro
   - /tmp/${COMPOSE_PROJECT_NAME}_uhome:/tmp
  working_dir: /cs
  command: ./startPlugins.sh
  environment:
   PYTHONUNBUFFERED: "1"
   TIM_ROOT: ${TIM_ROOT}
   COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
  user: root
 haskellplugins:
  image: timimages/haskellplugins:latest
  build:
   context: ./timApp/modules/Haskell
   dockerfile: Dockerfile
  volumes:
   - ./timApp/modules/Haskell:/Haskell
  working_dir: /Haskell
  command: ./startAll.sh
 showfile:
  image: timimages/svn:latest
  build: ./timApp/modules/svn
  volumes:
   - ./timApp/modules/svn:/svn:ro
   - ./timApp/modules/py:/py:ro
  working_dir: /svn
  command: ./startAll.sh
 imagex:
  image: timimages/cs3:compose
  volumes:
   - ./timApp/modules/imagex:/imagex:ro
   - ./timApp/modules/py:/py:ro
  working_dir: /imagex
  command: ./startAll.sh
 pali:
  image: timimages/pali:compose
  build: ./timApp/modules/pali
  volumes:
   - ./timApp/modules/pali:/pali:ro
   - ./timApp/modules/py:/py:ro
  working_dir: /pali
  command: ./startAll.sh
 uploader:
  image: villet/uploaderplugin:13_10_16_15
  command: ${UPLOADER_COMMAND}
 ts-watcher:
  image: timimages/tim:${TIM_IMAGE_TAG}
  volumes:
   - .:/service
  working_dir: /service/timApp/static/scripts
  command: jspm bundle tim/main + tim/slide - "(tim/main + tim/slide - [tim/**/*])" build/tim.js -wm
 nginx:
  image: timimages/local_nginx:compose
  build:
   context: ./local_nginx
  depends_on:
   - tim
  ports:
   - "${NGINX_PORT}:80"
  volumes:
   - ./timApp/modules/cs/static:/csstatic:ro
   - ./timApp/modules/cs/generated:/csgenerated:ro
   - ./timApp/static:/static:ro
 prebuilt_dumbo:
  image: timimages/prebuilt:latest
  volumes:
   - ./Ephemeral/Dumbo/dist/build/Dumbo:/target
  command: "cp /bin/Dumbo /target/"
volumes:
 data:
