version: "3.7"
services:
 tim:
  depends_on:
   - postgresql-test
  tmpfs:
   - /tmp
  command: "sleep infinity"
 postgresql:
  command: "sleep infinity"
 postgresql-test:
  image: postgres:11
  tmpfs:
   - /var/lib/postgresql/data
  environment:
   POSTGRES_PASSWORD: postgresql
 tests:
  image: timimages/tim:${TIM_IMAGE_TAG:?}
  command: "python3 -m unittest ${TEST_PARAMS:-discover tests/ 'test_*.py' .}"
  volumes:
   - .:/service:rw
  environment:
   TIM_SETTINGS: testconfig.py
   PYTHONPATH: /service
   GITLAB_CI: ${GITLAB_CI:-false}
  depends_on:
   - caddy
  tmpfs:
   - /tmp
   - /tim_files
   - /cache
  working_dir: /service/timApp
  read_only: true
# Disable some images and services that are not used in tests.
 stack-api-server:
  image: timimages/tim:${TIM_IMAGE_TAG:?}
  command: "sleep infinity"
 timagent:
  image: timimages/tim:${TIM_IMAGE_TAG:?}
  command: "sleep infinity"
