version: "3.7"
services:
 tim:
  depends_on:
   - ts
  tmpfs:
   - /run
 nginx:
  ports:
   - "${NGINX_PORT}:80"
 ts:
  image: timimages/tim:${TIM_IMAGE_TAG}
  volumes:
   - .:/service
   - /opt/jspm_cache:/root/.jspm
  working_dir: /service/timApp/static/scripts
  command: jspm bundle tim/main - "(tim/main - [tim/**/*])" build/tim.js -wm
  restart: unless-stopped
  read_only: true
 pali:
  environment:
    SHOW_TEMPLATES: "False"
