name: Check formatting

on: push

jobs:
  ts_format:
    name: Check TypeScript formatting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        run: |
          cd timApp
          rm package-lock.json
          npm install --unsafe-perm --legacy-peer-deps
          npm install --no-package-lock --legacy-peer-deps --no-save prettier@2.4.1
      - name: Check formatting
        run: cd timApp && npm run checkformat

  py_format:
    name: Check Python formatting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry
        run: pipx install --pip-args \'--pre\' poetry
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: poetry
      - name: Install dependencies
        run: poetry install --only=dev
      - name: Run format
        run: .venv/bin/black --check .